### ISSUE TITLE
Epic: Create `golem-core` usage examples to verify its design

### ISSUE THREAD

**Issue by approxit** [golemfactory/golem-core-python#59]
As first work item to start working with `golem-core` we decided to made some examples with it by whole team.

### Todo:
- [x] Propose example topics to create
  - Examples could use different levels of abstraction (low/mid/high)
- [ ] Collect reviews about golem-core usability, its architecture, or ideas about possible upgrades

```[tasklist]
### Examples
- [ ] #62
- [ ] #61
- [ ] #63
- [ ] #64
```

**Comment by lucekdudek** [comment]
Notes from 14.02.2023 refinement

Ideas:

- run task only on given set of providers 
- providers profiling: run tasks and rank providers by their ability - allow to choose providers that are the most reliable 
- discover provider's geo-location - allow to run next tasks in specific location (e.g. country)
- observe demands on the market - allows to gather data about traffic on golem 
- showcase what steps have to be complete in order to run simple task on golem - teaches how golem works
